FreeStyle_blog/django_blog/urls.py
from django.contrib import admin
from web.views import *
from backend.views import *
from django.urls import path
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainBlog/',mainBlog),
    path('giveLike/',giveLike),
    path('sign.html/',sign),
    path('login.html/',login, name="login"),
    path('logOut/',logOut),
    path('check_code/',checkCode),

    path('personalHomePage/<blogSite>/',personalHomePage),
    re_path('personalHomePage/(?P<blogSite>\w+)/(?P<condition>((date)|(category)|(tag)))/(?P<val>[0-9]+)/',personalClassPage),
    re_path('personalHomePage/(?P<blogSite>\w+)/(?P<condition>((date)|(category)|(tag)))/(?P<val>[0-9]+)/(?P<article_id>[0-9]+)/',oneArticle),
    re_path('personalHomePage/(?P<blogSite>\w+)/(?P<article_id>[0-9]+)/',oneArticle),

    path('backendManagement/<blogSite>/',backendManagement),
    re_path('backendManagement/(?P<blogSite>\w+)/(?P<blogCategory>((blog-)[0-9]+|(category-)[0-9]+))/',backendManagement),
    path('backendManagement/<blogSite>/createArticle.html/',createArticle),

    #普通用户，有创建，修改，删除功能
    re_path('backendManagement/(?P<blogSite>\w+)/troubleList.html/',trouble),
    re_path('backendManagement/(?P<blogSite>\w+)/createTrouble.html/',createTrouble),
    re_path('backendManagement/(?P<blogSite>\w+)/editTrouble-(?P<troubleId>[0-9]+).html/',editTrouble),
    re_path('backendManagement/(?P<blogSite>\w+)/detailTrouble-(?P<troubleId>[0-9]+).html/',detailTrouble),

    #超级用户
    re_path('backendManagement/(?P<blogSite>\w+)/troubleReport.html/',troubleReport),



]

FreeStyle_blog/repository/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    '''
    用户信息表
    '''
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名',max_length=32,unique=True)
    password = models.CharField(verbose_name='密码',max_length=64)
    nickname = models.CharField(verbose_name='昵称',max_length=32)
    email = models.EmailField(verbose_name='邮箱',unique=True)
    avatar = models.ImageField(verbose_name='头像',upload_to='static/userImage',null=True,blank=True)
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    fans = models.ManyToManyField(verbose_name='粉丝',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user','follower'))
    permissions = [
        (0, '普通'), (1, '管理'), (2, '最高'),
    ]
    premissions = models.IntegerField(choices=permissions,null=True,blank=True,default=0)
    class Meta:
        verbose_name="用户信息"
    def __str__(self):
        return self.username

class UserFans(models.Model):
    '''
    互粉关系表
    '''
    user = models.ForeignKey(verbose_name='博主',to='UserInfo',to_field='nid',
                             related_name='users',on_delete=models.CASCADE)
    follower = models.ForeignKey(verbose_name='粉丝',to='UserInfo',to_field='nid',
                                 related_name='follwers',on_delete=models.CASCADE)
    class Meta:
        verbose_name='互粉关系'
        unique_together = [
            ('user','follower'),
        ]
    def __str__(self):
        return self.user.username
class Blog(models.Model):
    '''
    博客信息
    '''
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题',max_length=64)
    site = models.CharField(verbose_name='个人博客前缀',max_length=32,unique=True)
    theme = models.CharField(verbose_name='博客主题',max_length=32)
    user = models.OneToOneField(to='UserInfo',to_field='nid',on_delete=models.CASCADE)

    class Meta:
        verbose_name = "博客信息"
    def __str__(self):
        return self.title

class Category(models.Model):
    '''
    博主博文分类表
    '''
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题',max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '博主博文分类'
    def __str__(self):
        return self.title

class Tag(models.Model):
    '''
    标签详情
    '''
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称',max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=models.CASCADE)

    class Meta:
        verbose_name='标签'
    def __str__(self):
        return self.title

class Artical(models.Model):
    '''
    文章详情
    '''
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题',max_length=32)
    summary = models.CharField(verbose_name='文章简介',max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(verbose_name='赞',default=0)
    down_count = models.IntegerField(verbose_name='踩',default=0)
    create_time = models.DateTimeField(verbose_name="发表时间")
    blog = models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=models.CASCADE)
    category = models.ForeignKey(verbose_name='文章类型',to='Category',to_field='nid',on_delete=models.SET('全部'))

    type_choices = [
        (1,'Python'),(2,'Linux'),(3,'OpenStack'),(4,'GoLang')
    ]
    article_type_id = models.IntegerField(choices=type_choices,default=None)
    tags = models.ManyToManyField(
        to='Tag',
        through='Article2Tag',
        through_fields=('article','tag'),
    )

    class Meta:
        verbose_name='文章详情'
    def __str__(self):
        return self.title

class ArticleDetail(models.Model):
    content = models.TextField(verbose_name='文章内容')
    artical = models.OneToOneField(verbose_name='所属文章',to='Artical',to_field='nid',on_delete=models.CASCADE)
    class Meta:
        verbose_name='文章内容详情'
    def __str__(self):
        return self.artical.title

class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章',to='Artical',to_field='nid',on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签',to='Tag',to_field='nid',on_delete=models.CASCADE)
    class Meta:
        verbose_name='文章标签信息'
        unique_together=[
            ('article','tag'),
        ]

class Comment(models.Model):
    '''
    评论表
    '''
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容',max_length=255)
    create_time = models.DateTimeField(verbose_name='评论时间',auto_now_add=True)

    reply = models.ForeignKey(verbose_name='评论回复',to='self',related_name='back',null=True,on_delete=models.CASCADE)
    article = models.ForeignKey(verbose_name='评论文章',to='Artical',to_field='nid',on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者',to='UserInfo',to_field='nid',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论表'

class UpDown(models.Model):
    '''
    顶或踩
    '''
    article = models.ForeignKey(verbose_name='文章',to='Artical',to_field='nid',on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='点赞者',to='UserInfo',to_field='nid',on_delete=models.CASCADE)
    up = models.BooleanField(verbose_name='是否赞')
    class Meta:
        verbose_name='点赞表'
        unique_together=[
            ('article','user'),
        ]

class Trouble(models.Model):
    title = models.CharField(verbose_name='报障标题', max_length=32)
    detail = models.CharField(verbose_name='报障详情', max_length=255)

    image = models.ImageField(verbose_name='报障图片', upload_to='static/disabilitiesImage', null=True,blank=True)
    user = models.ForeignKey(verbose_name='报障用户', to='UserInfo', to_field='nid',
                             on_delete=models.CASCADE, related_name='ud')

    handler = models.ForeignKey(verbose_name='处理用户', to='UserInfo', to_field='nid',
                                on_delete=models.CASCADE, related_name='hd', null=True,blank=True)
    status = [
        (0, '待处理'), (1, '处理中'), (2, '已处理'),
    ]
    handler_status = models.IntegerField(choices=status, default=0)
    cm_status = [
        (0, '很差'), (1, '一般'), (2, '很好')
    ]
    comment_status = models.IntegerField(choices=cm_status, default=1, null=True,blank=True)
    create_time = models.DateTimeField(verbose_name='提交时间', auto_now_add=True, null=False)
    dear_time = models.DateTimeField(verbose_name='处理时间',null=True,blank=True)
    dear_detail = models.TextField(null=True,blank=True)
    class Meta:
        verbose_name = '报障单'

    def __str__(self):
        return self.title

FreeStyle_blog/templates/blogPage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FreeStyleBlog</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %}">
    <style>
        .hotline{
            margin: 30px 0;
        }
        .login{
            float: right;
        }
        {% block sty %}
        {% endblock %}
    </style>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">FreeStyle技术论坛</a>
          {% block headline %}
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="/mainBlog">全部<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/mainBlog/?choice=1">Python<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/mainBlog/?choice=2">Linux</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/mainBlog/?choice=3">OpenStack</a>
          </li>
            <li class="nav-item">
            <a class="nav-link " href="/mainBlog/?choice=4">Golang</a>
          </li>
        <li class="nav-item">
            <a class="nav-link " href="/logOut/">注销</a>
          </li>
        </ul>
        <div id="loginAndSignLine">
             <a href="/login.html">登入</a>
             <a href="/sign.html">注册</a>
        </div>
          {% endblock %}
      </div>
        <div></div>
    </nav>

    {% block mainbody %}
    {% endblock %}

</div>

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>
<script>
    {% block upComment %}
    {% endblock %}
</script>
</body>
</html>

FreeStyle_blog/templates/blogPage/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
     <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css">
</head>
<body>
    <form class="container" href="/sign.html" method="post">
      <div class="form-group">
        <label for="exampleInputPassword1">用户名</label>
        {{ login_form.username }}
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">密码</label>
            {{ login_form.password }}
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">验证码</label>
          {{ login_form.check_code }} <img src="/check_code/" onclick="changeImage(this)" alt="">
      </div>
      <button type="submit" class="btn btn-primary a">提交</button>
</form>


<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script>
        $(function () {
            add();
        });
        function add() {
            var all_tag = $('form').find('input');
            $.each(all_tag,function (i) {
                if(i === 1){
                    $(this).attr({'class':'form-control','type':'password'});
                }else if(i === 0){
                    $(this).attr({'class':'form-control','type':'text'})
                }else
                    $(this).attr({'class':'form-control','type':'text'})

            })
        }
        function changeImage(th) {
            th.src = th.src + '?'
        }
    </script>


</body>
</html>

FreeStyle_blog/templates/blogPage/mainBlog.html
{% extends 'blogPage/base.html' %}

{% block sty %}
    .articleBody{
        height: 100px;
        overflow: hidden;
        margin: 0px 0px 2px 0px;
    }
    .avatar{
        width: 70px;
        height: 70px;
        float: left;
        margin: 0px 5px 0px 0px;
    }
    .artCotent{
        font-size: 14px;
        height: 70px;
    }
    .title{
        display: block;
        font-size: 16px;
        margin: 3px 0px;
        color: #20c997;
    }
    .btn{
        font-size: 13px;
    }
    .btcontain{
        margin: 0px 3px 0px 0px;
    }
{% endblock %}

{% block mainbody %}

    <div class="container">
        <div class="row">
            <div class="col-8">
                {% for article_obj in article_list %}
                    <div class="downline" btn="{{ article_obj.nid }} {{ article_obj.blog.user.nid }}" sessionData="{{ session_obj }}">

                        <div class="articleBody">
                            <div>
                                <a href="/personalHomePage/{{ article_obj.blog.site }}/{{ article_obj.nid }}/" class="title">{{ article_obj.title }}</a>
                                <img src="/{{ article_obj.blog.user.avatar }}" alt="" class="img-thumbnail avatar">
                                <div class="artotent text-justify">{{ article_obj.summary }}</div>
                            </div>
                        </div>
                        <span class="btn">
                        <span class="fa fa-user-o btcontain"></span>
                        <a href="/personalHomePage/{{ article_obj.blog.site }}/" class="btcontain">{{ article_obj.blog.title }}</a>
                        <span class="btcontain">{{ article_obj.create_time|date:"Y-m-d" }}</span>
                        <a class="fa fa-commenting-o btcontain"></a>
                        <span class="btcontain comment">{{ article_obj.comment_count }}</span>
                        <span class="fa fa-thumbs-o-up btcontain up"></span>
                        <span class="btcontain up_count">{{ article_obj.up_count }}</span>
                        </span>
                    </div>
                {% endfor %}
            </div>
            <div class="col-4">
                <div class="list-group hotline">
                      <a href="#" class="list-group-item list-group-item-info">
                        热门推荐
                      </a>
                      {% for obj in article_obj %}
                        <a href="/personalHomePage/{{ obj.blog.site }}/{{ obj.nid }}/" class="list-group-item list-group-item-action">{{ obj.title }}</a>
                      {% endfor %}
                </div>
            </div>

        </div>

        <nav aria-label="Page navigation example">
          <ul class="pagination">
              {% for pager in pager_obj.page_str %}
                {{ pager | safe }}
              {% endfor %}
          </ul>
        </nav>
    </div>

{% endblock %}

<script>
    $(function () {
        giveLike();
        sessionConfirm();

    });
    function giveLike() {
        console.log($(this).parent().attr('sessionData'));
       $('.up').click(function () {
           console.log($(this).parent())
           var sessionData = $(this).parent().attr('sessionData');
           console.log((sessionData))
           if(sessionData){
               articleData = $(this).parent().attr('btn');
               user_data = {'sessionData':sessionData,'articleData':articleData}
               console.log('aaaaaaaaaaaaaaa')
               submitBtn(this,user_data)
           }else {
               window.open('/login.html')
           }
       })
    }

    function submitBtn(th,user_data) {
        var tag = $(th).next();
        $.ajax({
               url:'/giveLike/',
               type:'GET',
               data:user_data,
                dataType:'JSON',
               success:function (arg) {
                   console.log(arg)
                   $(th).next().text(arg['data'])
               }
           })
    }

    function sessionConfirm() {
        var sessionData = $('.downline').attr('sessionData');
        if (sessionData){
            var tag = document.createElement('span');
            tag.innerHTML=sessionData;
            $('#loginAndSignLine').innerHTML.clear().append(tag)

        }
    }

</script>

{% block upComment %}
    $(function () {
        giveLike();
        sessionConfirm();
    });
    function giveLike() {
       $('.up').click(function () {
           var sessionData = $(this).parent().parent().attr('sessionData');
           console.log(sessionData)
           if(sessionData != 'None'){
               articleData = $(this).parent().parent().attr('btn');
               user_data = {'sessionData':sessionData,'articleData':articleData}
               submitBtn(this,user_data)
           }else {
               window.open('/login.html')
           }
       })
    }

    function submitBtn(th,user_data) {
        var tag = $(th).next();
        $.ajax({
               url:'/giveLike/',
               type:'GET',
               data:user_data,
               dataType:'JSON',
               success:function (arg) {
               console.log('1231321231')
                   $(th).next().text(arg["data"])
               }
           })
    }
    function sessionConfirm() {
        var sessionData = $('.downline').attr('sessionData');
        console.log('..........')
        console.log(sessionData)
        if (sessionData != 'None'){
            $('#loginAndSignLine').children().remove()
            $('#loginAndSignLine').text('Wellcome'+' '+sessionData)
            console.log($('#loginAndSignLine').text())
        }
    }

{% endblock %}

FreeStyle_blog/templates/blogPage/oneArticle.html
{% extends 'blogPage/personalHomePage.html' %}

{% block articleContent %}

    <div class="col-9">
        <div>
            <h2>{{ artical_obj.title }}</h2>
            <p>{{ artical_obj.articledetail.content }}</p>
        </div>
        <div class="upAndComment">
            <a href="" class="fa fa-thumbs-o-up articalUpDown"></a>
            <a href="" class="fa fa-thumbs-o-down articalUpDown"></a>
        </div>
        <div>{{ artical_obj.create_time }} &emsp;
            <a href="">{{ artical_obj.blog.title }}</a>
            &emsp;评论(0)&emsp;阅读(0)
        </div>
        <div>
            <img src="/{{ artical_obj.blog.user.avatar }}"class="headImage" alt="">
            <span>{{ artical_obj.blog.user.username }}</span>
            <span>aaaaaaaaaaaaaaaaaaaaa</span>
            <span>本文版权作者所有，欢迎转载，且在的姐姐姐姐</span>
        </div>
        <div class="commentResponse">评论回复</div>

        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% for pager in pager_obj.page_str %}
                    {{ pager | safe }}
                {% endfor %}
            </ul>
        </nav>

        <div>
            <textarea name="content" id="content"></textarea>
        </div>
        <span>提交</span>
    </div>

{% endblock %}

{% block articleCss %}

    <style>
        .upAndComment{
            height: 60px;
            color: #0062cc;
            font-size: 30px;
        }
        .articalUpDown{
            display: inline-block;
            width: 40px;
            height: 50px;
            line-height: 50px;
            border: #9fcdff 1px solid;
        }
        .commentResponse{
            height: 160px;
            background: #20c997;
        }
        .headImage{
            width: 60px;
            height: 60px;
        }
    </style>

{% endblock %}

<script>
        $(function () {
            initKindEditor();
        });
        function initKindEditor() {
           var kind = KindEditor.create('#content',{
               width:'100%',
               height:'200px',
               minWidth:200,
               minHeight:200
           })
        }
</script>

FreeStyle_blog/templates/blogPage/personalHomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %}">

    <style>
        .handLineAll{
            background: darkseagreen;
            height: 70px;
            width: 90%;
            position: relative;
        }
        .handlineBlog{
            font-size: 30px;
            line-height: 50px;
            width: 30%;
            float: left;
        }
        .handlineTheme{
            width: 40%;
            float: left;
            margin: 20px auto;

        }
        .handlineOperate{
            width: 30%;
            float: left;

        }
        .operateArguement{
            float: right;
            position: relative;
            bottom: -40px;

        }
        .personalBody{
            clear: both;
        }
        .article_content{
            height: 60px;
            overflow: hidden;
            font-size: 14px;
        }

    </style>
    {% block articleCss %}
        {% endblock %}
</head>
<body>

    <div class="container handLineAll">
        <div class="handlineBlog">
            <p>{{ blog_obj.site }}</p>
        </div>
        <div class="handlineTheme"><p>时间是最好的检查官,因为从来不停止</p>
        </div>
        <div class="handlineOperate">
            <div class="operateArguement">
                <a href="/mainBlog/">首页</a>
                <a href="/personalHomePage/{{ login_obj.blog.site }}/">个人首页</a>
                <a href="/backendManagement/{{ login_obj.blog.site }}/">管理</a>
            </div>
        </div>
    </div>



    <div class="container personalBody">
        <div class="row">
            <div class="col-3">

            <div class="card" style="width: 247.5px;">
                 <div class="card-body">
                     <h5 class="card-title">公告</h5>
                     <ul>
                         <li>昵称: </li>
                         <li>粉丝: </li>
                         <li>邮箱：</li>
                     </ul>
                     <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
            </div>

            <div class="card" style="width: 247.5px;">
                <div class="card-body">
                    <h5 class="card-title">标签</h5>
                    <ul>
                        {% for tag in blog_obj.tag_set.all %}
                            <li><a href="/personalHomePage/{{ blog_obj.site }}/tag/{{ tag.nid }}">{{ tag.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="card" style="width: 247.5px;">
                <div class="card-body">
                    <h5 class="card-title">分类
                    </h5>
                    <ul>
                        {% for category in blog_obj.category_set.all %}
                        <li><a href="/personalHomePage/{{ blog_obj.site }}/category/{{ category.nid }}" class="card-link">{{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="card" style="width: 247.5px;">
                 <div class="card-body">
                     <h5 class="card-title">时间</h5>
                     <ul>
                         <li><a href="#" class="card-link">Card link</a></li>
                         <li><a href="#" class="card-link">Another link</a></li>
                     </ul>
                 </div>
            </div>
            </div>


        {% block articleContent %}
            <div class="col-9">

                {% for artical_obj in all_artical_list %}
                <a href="/personalHomePage/{{ artical_obj.blog.site }}/{{ artical_obj.nid }}/">{{ artical_obj.title }}</a>
                <div class="article_content">
                    <p>{{ artical_obj.articledetail.content }}</p>
                </div>
                <div>
                    <span>{{ artical_obj.create_time }}</span>
                    <span>阅读(0)</span>
                    <span><a href="">评论</a>(0)</span>
                    <span><a href="">点赞</a>(0)</span>
                </div>
            {% endfor %}

                <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% for pager in pager_obj.page_str %}
                        {{ pager | safe }}
                {% endfor %}
                </ul>
                </nav>

            </div>
        {% endblock %}
        </div>
    </div>



<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>
<script src="{% static 'plugins/kindeditor-4.1.10/kindeditor-all.js' %}"></script>
{% block articalJs %}
{% endblock %}
</body>
</html>

FreeStyle_blog/templates/blogPage/sign.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css">
</head>
<body>
<div>

    <form class="container" href="/sign.html" method="post">
      <div class="form-group">
        <label for="exampleInputPassword1">用户名</label>
        {{ sign_obj.username }}{{ sign_obj.errors.username.0 }}{{ verify_data.message }}
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">密码</label>
            {{ sign_obj.password }}{{ sign_obj.errors.password.0 }}{{ sign_obj.non_field_errors.0 }}
      </div>
        <div class="form-group">
        <label for="exampleInputPassword1">再次输入密码</label>
            {{ sign_obj.confirm_password }}{{ sign_obj.errors.confirm_password.0 }}
      </div>

      <div class="form-group">
        <label for="exampleInputPassword1">邮箱</label>
          {{ sign_obj.email }}{{ sign_obj.errors.email.0 }}{{ verify_data.message }}
      </div>
      <button type="submit" class="btn btn-primary a">提交</button>
</form>









    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script>

        var all_tag = $('form').find('input');
        function add() {
            $.each(all_tag,function (i) {
                if(i === 1 || i === 2){
                    $(this).attr({'class':'form-control','type':'password'});
                }else if(i === 0){
                    $(this).attr({'class':'form-control','type':'text'})
                }else
                    $(this).attr({'class':'form-control','type':'email'})

            })
        }

        add()
    </script>
</div>
</body>
</html>