FreeStyle_blog/django_blog/urls.py
from django.contrib import admin
from web.views import *
from backend.views import *
from django.urls import path
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainBlog/',mainBlog),
    path('giveLike/',giveLike),
    path('sign.html/',sign),
    path('login.html/',login, name="login"),
    path('logOut/',logOut),
    path('check_code/',checkCode),

    path('personalHomePage/<blogSite>/',personalHomePage),
    re_path('personalHomePage/(?P<blogSite>\w+)/(?P<condition>((date)|(category)|(tag)))/(?P<val>[0-9]+)/',personalClassPage),
    re_path('personalHomePage/(?P<blogSite>\w+)/(?P<condition>((date)|(category)|(tag)))/(?P<val>[0-9]+)/(?P<article_id>[0-9]+)/',oneArticle),
    re_path('personalHomePage/(?P<blogSite>\w+)/(?P<article_id>[0-9]+)/',oneArticle),

    path('backendManagement/<blogSite>/',backendManagement),
    re_path('backendManagement/(?P<blogSite>\w+)/(?P<blogCategory>((blog-)[0-9]+|(category-)[0-9]+))/',backendManagement),
    path('backendManagement/<blogSite>/createArticle.html/',createArticle),

    #普通用户，有创建，修改，删除功能
    re_path('backendManagement/(?P<blogSite>\w+)/troubleList.html/',trouble),
    re_path('backendManagement/(?P<blogSite>\w+)/createTrouble.html/',createTrouble),
    re_path('backendManagement/(?P<blogSite>\w+)/editTrouble-(?P<troubleId>[0-9]+).html/',editTrouble),
    re_path('backendManagement/(?P<blogSite>\w+)/detailTrouble-(?P<troubleId>[0-9]+).html/',detailTrouble),

    #超级用户
    re_path('backendManagement/(?P<blogSite>\w+)/troubleReport.html/',troubleReport),



]

FreeStyle_blog/repository/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    '''
    用户信息表
    '''
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名',max_length=32,unique=True)
    password = models.CharField(verbose_name='密码',max_length=64)
    nickname = models.CharField(verbose_name='昵称',max_length=32)
    email = models.EmailField(verbose_name='邮箱',unique=True)
    avatar = models.ImageField(verbose_name='头像',upload_to='static/userImage',null=True,blank=True)
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    fans = models.ManyToManyField(verbose_name='粉丝',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user','follower'))
    permissions = [
        (0, '普通'), (1, '管理'), (2, '最高'),
    ]
    premissions = models.IntegerField(choices=permissions,null=True,blank=True,default=0)
    class Meta:
        verbose_name="用户信息"
    def __str__(self):
        return self.username

class UserFans(models.Model):
    '''
    互粉关系表
    '''
    user = models.ForeignKey(verbose_name='博主',to='UserInfo',to_field='nid',
                             related_name='users',on_delete=models.CASCADE)
    follower = models.ForeignKey(verbose_name='粉丝',to='UserInfo',to_field='nid',
                                 related_name='follwers',on_delete=models.CASCADE)
    class Meta:
        verbose_name='互粉关系'
        unique_together = [
            ('user','follower'),
        ]
    def __str__(self):
        return self.user.username
class Blog(models.Model):
    '''
    博客信息
    '''
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题',max_length=64)
    site = models.CharField(verbose_name='个人博客前缀',max_length=32,unique=True)
    theme = models.CharField(verbose_name='博客主题',max_length=32)
    user = models.OneToOneField(to='UserInfo',to_field='nid',on_delete=models.CASCADE)

    class Meta:
        verbose_name = "博客信息"
    def __str__(self):
        return self.title

class Category(models.Model):
    '''
    博主博文分类表
    '''
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题',max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '博主博文分类'
    def __str__(self):
        return self.title

class Tag(models.Model):
    '''
    标签详情
    '''
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称',max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=models.CASCADE)

    class Meta:
        verbose_name='标签'
    def __str__(self):
        return self.title

class Artical(models.Model):
    '''
    文章详情
    '''
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题',max_length=32)
    summary = models.CharField(verbose_name='文章简介',max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(verbose_name='赞',default=0)
    down_count = models.IntegerField(verbose_name='踩',default=0)
    create_time = models.DateTimeField(verbose_name="发表时间")
    blog = models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=models.CASCADE)
    category = models.ForeignKey(verbose_name='文章类型',to='Category',to_field='nid',on_delete=models.SET('全部'))

    type_choices = [
        (1,'Python'),(2,'Linux'),(3,'OpenStack'),(4,'GoLang')
    ]
    article_type_id = models.IntegerField(choices=type_choices,default=None)
    tags = models.ManyToManyField(
        to='Tag',
        through='Article2Tag',
        through_fields=('article','tag'),
    )

    class Meta:
        verbose_name='文章详情'
    def __str__(self):
        return self.title

class ArticleDetail(models.Model):
    content = models.TextField(verbose_name='文章内容')
    artical = models.OneToOneField(verbose_name='所属文章',to='Artical',to_field='nid',on_delete=models.CASCADE)
    class Meta:
        verbose_name='文章内容详情'
    def __str__(self):
        return self.artical.title

class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章',to='Artical',to_field='nid',on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签',to='Tag',to_field='nid',on_delete=models.CASCADE)
    class Meta:
        verbose_name='文章标签信息'
        unique_together=[
            ('article','tag'),
        ]

class Comment(models.Model):
    '''
    评论表
    '''
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容',max_length=255)
    create_time = models.DateTimeField(verbose_name='评论时间',auto_now_add=True)

    reply = models.ForeignKey(verbose_name='评论回复',to='self',related_name='back',null=True,on_delete=models.CASCADE)
    article = models.ForeignKey(verbose_name='评论文章',to='Artical',to_field='nid',on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者',to='UserInfo',to_field='nid',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论表'

class UpDown(models.Model):
    '''
    顶或踩
    '''
    article = models.ForeignKey(verbose_name='文章',to='Artical',to_field='nid',on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='点赞者',to='UserInfo',to_field='nid',on_delete=models.CASCADE)
    up = models.BooleanField(verbose_name='是否赞')
    class Meta:
        verbose_name='点赞表'
        unique_together=[
            ('article','user'),
        ]

class Trouble(models.Model):
    title = models.CharField(verbose_name='报障标题', max_length=32)
    detail = models.CharField(verbose_name='报障详情', max_length=255)

    image = models.ImageField(verbose_name='报障图片', upload_to='static/disabilitiesImage', null=True,blank=True)
    user = models.ForeignKey(verbose_name='报障用户', to='UserInfo', to_field='nid',
                             on_delete=models.CASCADE, related_name='ud')

    handler = models.ForeignKey(verbose_name='处理用户', to='UserInfo', to_field='nid',
                                on_delete=models.CASCADE, related_name='hd', null=True,blank=True)
    status = [
        (0, '待处理'), (1, '处理中'), (2, '已处理'),
    ]
    handler_status = models.IntegerField(choices=status, default=0)
    cm_status = [
        (0, '很差'), (1, '一般'), (2, '很好')
    ]
    comment_status = models.IntegerField(choices=cm_status, default=1, null=True,blank=True)
    create_time = models.DateTimeField(verbose_name='提交时间', auto_now_add=True, null=False)
    dear_time = models.DateTimeField(verbose_name='处理时间',null=True,blank=True)
    dear_detail = models.TextField(null=True,blank=True)
    class Meta:
        verbose_name = '报障单'

    def __str__(self):
        return self.title

FreeStyle_blog/templates/blogManagement/createArticle.html
{% extends 'blogManagement/layout.html' %}

{% block articleCss %}
    <style>
        .article-create-backend{
            background: white;
            width: 100%;
            height: 100%;
        }
        .article-create-btn{
            background: white;
        }
    </style>
{% endblock %}

{% block backendContent %}

    <div class="article-create-backend">
        <div class="pg-content-mainu">
            <a href="">文章管理</a>/
            <a href="">文章列表</a>
        </div>
        <form action="/backendManagement/{{ blogSite }}/createArticle.html/" method="post">
            <p>标题</p> {{ createForm.errors.title.0 }}
            <p>{{ createForm.title }}</p>
            <p>简介</p> {{ createForm.summary.title.0 }}
            <p>{{ createForm.summary }}</p>
            <p>内容</p> {{ createForm.articledatail_content.title.0 }}
            <p>{{ createForm.articledetail_content }}</p>
            <div class="article-create-btn">
                <p>类型</p> {{ createForm.errors.article_type_id.0 }}
                <p>{{ createForm.article_type_id }}</p>
                <p>分类</p> {{ createForm.errors.category_id.0 }}
                <p>{{ createForm.category_id }}</p>
                <p>标签</p> {{ createForm.errors.tag_id.0 }}
                <p>{{ createForm.tag_id }}</p>
            </div>

            <input type="submit" class="btn btn-primary" value="保存">

        </form>
    </div>
    <div>
    </div>

{% endblock %}

{% block articalJs %}
    <script>
        $(function () {
            initKindEditor();
        });
        function initKindEditor() {
           var kind = KindEditor.create('#content',{
               width:'100%',
               height:'200px',
               minWidth:200,
               minHeight:200
           })
        }
    </script>
{% endblock %}

FreeStyle_blog/templates/blogManagement/dearTrouble.html
{% extends 'blogManagement/layout.html' %}

{% block backendContent %}
        <div class="pg-content-mainu">
            <a href="">报障管理</a>/
            <a href="">报障处理</a>
        </div>
        <div class="pg-content-search">
            <div>
                <p>标题</p>
                <p>{{ troubleObj.title }}</p>
            </div>
            <div>
                <p>内容</p>
                <p>{{ troubleObj.detail }}</p>
            </div>
            <div>
                <form action="backendManagement/{{ blogSite }}/dearTrouble-{{ troubleObj.id }}.html/" method="post">
                    {{ dearFormObj.dear_detail }}
                    <input type="submit">
                </form>
            </div>
        </div>

{% endblock %}

{% block articalJs %}
    <script>
        $(function () {
            initKindEditor();
        });
        function initKindEditor() {
           var kind = KindEditor.create('#dear-trouble',{
               width:'100%',
               height:'200px',
               minWidth:200,
               minHeight:200
           })
        }
    </script>
{% endblock %}

FreeStyle_blog/templates/blogManagement/detailTrouble.html
{% extends 'blogManagement/layout.html' %}

    {% block articleCss %}
        <style>
            .pg-content-trouble .trouble-title-content{
                background: white;

            }
            .pg-content-trouble .trouble-title-content .trouble-title{
                font-size: 20px;
                text-align: center;
                margin-bottom: 0;

            }
            .pg-content-trouble .trouble-title-content .create-detail{
                text-align: center;
                font-size: 14px;
            }
        </style>
    {% endblock %}

{% block backendContent %}
    <div class="pg-content-mainu">
        <a href="">保障管理</a>/
        <a href="">保障详情</a>
    </div>
    <div class="pg-content-trouble">
        <div class="trouble-title-content">
            <p class="trouble-title">{{ trouble_obj.title }}</p>
            <div class="create-detail">
                <span>{{ trouble_obj.user.username }}</span><span>{{ trouble_obj.create_time|date:'Y-m-d' }}</span>
            </div>
        </div>
        <div class="trouble-detail">
            <p>{{ trouble_obj.detail }}</p>
        </div>

        <div class="trouble-results">
            <p>处理结果</p>
            <p>{{ trouble_obj.dear_detail }}</p>
            <p>{{ trouble_obj.handler.username }}</p>
            <span>处理人</span>
            <p>{{ trouble_obj.dear_time|date:'Y-m-d' }}</p>
            <span>处理时间</span>
        </div>
    </div>
{% endblock %}

FreeStyle_blog/templates/blogManagement/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/layout.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %}">
    <style>
        *{
            margin: 0;
        }
        .head-title{
            height: 60px;
            background: #60c9ba;
            min-width: 1100px;
            line-height: 60px;
            color: white;
        }
        .right{
            float: right;
        }
        .left{
            float: left;
        }
        .head-tag{
            width: 18%;
            background: #57ac9d;
            text-align: center;
            font-size: 20px;
        }
        .head-list,.head-opreate{
            font-size: 14px;
            color: white;
        }
        .head-title .head-list .title{
            color: white;
            padding: 0 10px;
            display: inline-block;
        }
        .head-title .head-list .title:hover{
            background: #57ac9d;
        }
        .head-title .head-list .title-list{
            display: inline-block;
            position: relative;
        }
        .head-title .head-list .title-list .child-title{
            position: absolute;
            background: #9fcdff;
            width: 69px;
            height: 120px;
            text-align: center;
            display: none;
        }
        .head-title .head-list .title-list .child-title a{
            display: block;
            line-height: 30px;
        }
        .head-title .head-list .title-list:hover .child-title{
            display: block;
        }
        .head-opreate .user-image{
            display: inline-block;
            line-height: 30px;
            float: right;
            position: relative;
            top: 8px;
        }
        .user-image .image-mainu{
            position: absolute;
            top: 44px;
            width: 56px;
            right: -14px;
            display: none;
            background: #b3d7ff;
        }
        .head-opreate .user-image:hover .image-mainu{
            display: inline-block;
        }
        .head-opreate .user-image .image-one{
            float: right;
            border-radius: 50%;
            top: 4px;

        }

        .head-title .head-opreate{
            padding: 0 20px;
        }
        .head-title .head-opreate .operate{
            display: inline-block;
            padding: 0 10px;
            color: white;
        }
        .head-title .head-opreate .operate:hover{
            background: #57ac9d;
        }
        .pg-body .mainu{
            position: absolute;
            width: 223px;
            background: #f2f8ff;
            bottom: 0;
            left: 0;
            top: 60px;
            color: #60c9ba;
            text-align: center;
            padding: 20px 0;
        }
        .pg-body .content{
            position: absolute;
            top: 60px;
            bottom: 0;
            left: 229px;
            right: 0;
            overflow: scroll;
            background: rgba(38, 54, 35, 0.06);
        }
        .pg-body .mainu .mainu-list a{
            display: block;
        }
        .pg-body .mainu .mainu-list{
            display: none;
        }
        .pg-body .mainu .mainu-title{
            margin: 4px 0;
        }

        .pg-content-mainu{
            line-height: 40px;
            margin: 0 10px;
            border-bottom: lightgrey 1px dashed;
            font-size: 15px;
        }
        .search-title{
            border-bottom: lightgrey 1px dashed;
            background: white;
            line-height: 40px;
            font-size: 13px;
        }
        .search-list{
            height: 100px;
            background: white;
        }

        .search-list .search-condions{
            padding: 10px;
            font-size: 14px;
        }
        .search-list .search-condions span{
            margin: 0 10px;
        }
        .search-list .search-condions span a{
            margin: 0 10px;
        }
        .result-list{
            background: white;
        }
        .article-operate span{
            background: #77a4bf;
            font-size: 12px;
            color: white;
            display: inline-block;
            width: 45px;
            line-height: 25px;
            border-radius: 10%;
            text-align: center;
        }
        .pg-content-search .result-title{
            line-height: 40px;
            font-size: 13px;
        }
        .pg-content-search .result-title span{
            display: inline-block;
            margin: 0 4px;
            line-height: 20px;
        }
        .pg-content-search .result-title .create-article-btn{
            display: inline-block;
            background: #60c9ba;
            float: right;
            margin: 0 6px;
            color: white;
            font-size: 13px;
        }
        .pg-content-search .result-title .create-article-btn:hover{
            background: #57ac9d;
        }
    </style>
    {% block articleCss %}

    {% endblock %}
</head>
<body>

<div class="text"></div>
<div class="head-title">
    
    <div class="head-tag left">FreeStyle技术博客</div>
    
    <div class="head-list left">
        <a href="/mainBlog/" class="title">博客首页</a>
        <a class="title">标题一</a>
        <a class="title">标题一</a>
        <div class="title-list">
            <a href="/personalHomePage/{{ login_obj.blog.site }}/">个人首页</a>
            <div class="child-title">
                <a href="">菜单一 </a>
                <a href="">菜单二</a>
                <a href="">菜单三</a>
            </div>
        </div>
    </div>
    
    <div class="head-opreate right">
        <a class="operate" href="">任务</a>
        <a class="operate" href="">通知</a>
        <a class="operate" href="">消息</a>
        <div class="user-image">
            <img class="image-one" src="/static/userImage/default.png" alt="">
            <div class="image-mainu">
                <a href="">菜单一 </a>
                <a href="">菜单二</a>
                <a href="">菜单三</a>
            </div>
        </div>

    </div>
</div>

<div class="pg-body">
    <div class="mainu">
        <div class="mainu-title">文章管理</div>
        <div class='mainu-list'>
            <a href="/backendManagement/{{ blogSite }}/">文章管理</a>
        </div>
        <div class="mainu-title">分类管理</div>
        <div class='mainu-list'>
            <a href="">文章管理</a>
        </div>
        <div class="mainu-title">标签管理</div>
        <div class='mainu-list'>
            <a href="">文章管理</a>
        </div>
        <div class="mainu-title">个人信息</div>
        <div class='mainu-list'>
            <a href="">文章管理</a>
        </div>
        <div class="mainu-title">保障信息</div>
        <div class="mainu-list">
            <a href="/backendManagement/{{ blogSite }}/troubleList.html/">报障清单</a>
            <a href="">文章管理</a>
        </div>
    </div>
    <div class="content">
        {% block backendContent %}
        <div class="pg-content-mainu">
            <a href="">文章管理</a>/
            <a href="">文章列表</a>
        </div>
        <div class="pg-content-search">
            <div class="search-title">
                <span class="fa fa-search"></span>搜索条件
            </div>

            <div class="search-list">
                <div class="search-condions">
                    <span>全部</span>
                    <span>
                        {% for blog_category in article_obj.type_choices %}
                        <a href="/backendManagement/{{ blogSite }}/blog-{{ blog_category.0 }}/">{{ blog_category.1 }}</a>
                        {% endfor %}
                    </span>
                </div>
                <div class="search-condions">
                    <span>全部</span>
                    <span>
                        {% for article_category in article_category_obj  %}
                        <a href="/backendManagement/{{ blogSite }}/category-{{ article_category.nid }}/">{{ article_category.title }}</a>
                        {% endfor %}
                    </span>
                </div>
            </div>
            <div class="result-title">
                <span class="fa fa-book"></span>
                <span class="search-article"></span>搜索文章()
                <a href="/backendManagement/{{ blogSite }}/createArticle.html/" class="create-article-btn">
                    <span class="fa fa-plus"></span>
                    <span>创建新文章</span>
                </a>
            

            </div>
            <div class="result-list">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">文章标题</th>
                            <th scope="col">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for article_obj in article_category_list %}
                        <tr>
                            <td>{{ article_obj.title }}</td>
                            <td class="article-operate">
                                <span class="fa fa-remove">删除</span>|
                                <span class="fa fa-edit">编辑</span>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>


        {% endblock %}
    </div>
</div>




<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/plugins/bootstrap/js/bootstrap.js"></script>
<script src="{% static 'plugins/kindeditor-4.1.10/kindeditor-all.js' %}"></script>
<script>
    $(function () {
        MainuShow();
    });
    function MainuShow() {
        $('.mainu-title').on('click',$('.mainu-list'),function () {
            if($(this).next().css('display')==='none'){
                $('.mainu-list').css('display','none');
                $(this).next().css('display','block');
            }else {
                $(this).next().css('display','none');
            }
        })
    }
</script>
{% block articalJs %}

{% endblock %}

</body>
</html>

FreeStyle_blog/templates/blogManagement/troubleCreate.html
{% extends 'blogManagement/layout.html' %}



{% block backendContent %}

    <form action="/backendManagement/{{ blogSite }}/createTrouble.html/" method="post" enctype="multipart/form-data">
        <div>
            <label>标题</label>
            <p>{{ troubleFormObj.title }}</p>{{ troubleFormObj.errors.title.0 }}
        </div>
        <div>
            <label>详情</label>
            <p>{{ troubleFormObj.detail }}</p>{{ troubleFormObj.errors.detail.0 }}
        </div>
        <div>
            <label>图片</label>
            <p>{{ troubleFormObj.image }}</p>{{ troubleFormObj.errors.image.0 }}
        </div>
        <input type="submit" value="提交">
    </form>

{% endblock %}

{% block articalJs %}
    <script>
        $(function () {
            initKindEditor();
        });
        function initKindEditor() {
           var kind = KindEditor.create('#trouble',{
               width:'100%',
               height:'200px',
               minWidth:200,
               minHeight:200
           })
        }
    </script>
{% endblock %}

FreeStyle_blog/templates/blogManagement/troubleEdit.html
{% extends 'blogManagement/layout.html' %}



{% block backendContent %}

    <form action="/backendManagement/{{ blogSite }}/editTrouble-{{ troubleObj.id }}.html/" method="post" enctype="multipart/form-data">
        <div>
            <label>标题</label>
            <p>{{ troubleFormObj.title }}</p>{{ troubleFormObj.errors.title.0 }}
        </div>
        <div>
            <label>详情</label>
            <p>{{ troubleFormObj.detail }}</p>{{ troubleFormObj.errors.detail.0 }}
        </div>
        <div>
            <label>图片</label>
            <img src="{{ troubleObj.image }}" alt="">
            <p>{{ troubleFormObj.image }}</p>{{ troubleFormObj.errors.image.0 }}
        </div>
        <input type="submit" value="提交">
    </form>

{% endblock %}

{% block articalJs %}
    <script>
        $(function () {
            initKindEditor();
        });
        function initKindEditor() {
           var kind = KindEditor.create('#trouble',{
               width:'100%',
               height:'200px',
               minWidth:200,
               minHeight:200
           })
        }
    </script>
{% endblock %}

FreeStyle_blog/templates/blogManagement/troubleList.html
{% extends 'blogManagement/layout.html' %}


{% block articleCss %}
    <style>
        .create-trouble-btn{
            float: right;
            margin: 3px 5px;
        }
        .create-trouble-btn a{
            color: white;
        }
        .article-operate span{
            width: 80px;
        }
        .article-operate span a{
            color: white;
        }
    </style>


{% endblock %}

{% block backendContent %}
    <div class="pg-content-mainu">
        <a href="">报障管理</a>/
        <a href="">报障列表</a>
    </div>
    <div class="trouble-list">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">报障标题</th>
                    <th scope="col">状态</th>
                    <th scope="col">创建时间</th>
                    <th scope="col">处理时间</th>
                    <th scope="col">处理人</th>
                    <th scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
                {% for trouble_obj in trouble_list %}
                    <tr>
                        <td><a href="">{{ trouble_obj.title }}</a></td>
                        <td>{{ trouble_obj.get_handler_status_display }}</td>
                        <td>{{ trouble_obj.create_time|date:'Y-m-d' }}</td>
                        <td>{{ trouble_obj.dear_time|date:'Y-m-d' }}</td>
                        <td>{{ trouble_obj.handler }}</td>
                        <td class="article-operate">
                        {% if blogSite == 'root' %}
                            {% if trouble_obj.handler_status == 0 %}
                                <span class="fa fa-mortar-board"><a href="/backendManagement/{{ blogSite }}/dearTrouble-{{ trouble_obj.id }}.html/">接单</a></span>
                            {% elif trouble_obj.handler_status == 1 %}
                                <span class="fa fa-mortar-board"><a href="/backendManagement/{{ blogSite }}/dearTrouble-{{ trouble_obj.id }}.html/">处理</a></span>
                            {% else %}
                                <span class="fa fa-mortar-board"><a href="/backendManagement/{{ blogSite }}/detailTrouble-{{ trouble_obj.id }}.html/">查看处理</a></span>
                            {% endif %}
                        {% elif trouble_obj.handler_status == 2 %}
                                <span class="fa fa-mortar-board"><a href="/backendManagement/{{ blogSite }}/detailTrouble-{{ trouble_obj.id }}.html/">查看处理</a></span>
                        {% endif %}
                            <span class="fa fa-remove">删除</span>|
                            <span class="fa fa-edit"><a href="/backendManagement/{{ blogSite }}/editTrouble-{{ trouble_obj.id }}.html/">编辑</a></span>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="create-trouble-btn btn btn-info">
            <i class="fa fa-plus"></i>
            <a href="/backendManagement/{{ blogSite }}/createTrouble.html/">创建保障单</a>
        </div>
    </div>

{% endblock %}

FreeStyle_blog/templates/blogManagement/troubleReport.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div id="container" style="min-width:400px;height:400px"></div>


<script src="/static/plugins/Highcharts-6.1.1/code/highcharts.js"></script>
<script>
    var chart = Highcharts.chart('container', {
    chart: {
        type: 'line'
    },
    title: {
        text: '报障接单表'
    },
    subtitle: {
        text: '数据来源: Wo rldClimate.com'
    },
    xAxis: {
        categories: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
    },
    yAxis: {
        title: {
            text: '处理数量 (°C)'
        }
    },
    plotOptions: {
        line: {
            dataLabels: {
                // 开启数据标签
                enabled: true
            },
            // 关闭鼠标跟踪，对应的提示框、点击事件会失效
            enableMouseTracking: false
        }
    },
    series: [{
        name: 'root',
        data: [7.0, 6.9, 9.5, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
    }, {
        name: 'superUser',
        data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
    }]
});

</script>
</body>
</html>